version: "1.0"

services:
    postgres:
        image: "postgres:latest"
        container_name: postgres
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_DB=app_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: "pg_isready -U postgres"
        networks:
            - notes-network

    keycloak:
        image: quay.io/keycloak/keycloak:22.0.5
        container_name: keycloak-auth
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=postgres
            - KC_DB_URL_HOST=postgres
            - KC_DB_URL_DATABASE=app_db
            - KC_DB_USERNAME=postgres
            - KC_DB_PASSWORD=postgres
            - KC_HEALTH_ENABLED=true
        ports:
            - "8081:8080"
        command: "start-dev --proxy=edge --hostname-strict=false "
        depends_on:
            - postgres
        networks:
            - notes-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        ports:
            -   "8080:8080"
        depends_on:
            -   keycloak
            -   postgres
        networks:
            - notes-network
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_db
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

networks:
    notes-network:
        driver: bridge